### ISSUE TITLE
geocoding api url not working

### ISSUE THREAD

**Issue by srikanth1184** [smnirven/geocoding_example#1]
Getting the following exception when I run the app and hit the button.

java.io.FileNotFoundException: http://maps.google.com/maps/geo?q=17.357693120476622,78.46111164790031&output=xml&oe=utf8&sensor=true&key=2130968578
at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:197)
at example.geocoding.Geocoder.reverseGeocode(Geocoder.java:44)
at example.geocoding.Main$ReverseGeocodeLookupTask.doInBackground(Main.java:130)
at example.geocoding.Main$ReverseGeocodeLookupTask.doInBackground(Main.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)

**Comment by smnirven** [comment]
@srikanth1184 when i try the url you pasted there, I get a response from Google that looks like you hit a rate limit issue with that API key. https://support.google.com/websearch/answer/86640
